package com.common.tools.util;


import static com.common.tools.util.exception.BusinessExceptionAssert.USER_NOT_FOUND;

import com.common.tools.util.exception.BaseException;
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Builder Tester.
 *
 * @author <Authors name>
 * @version 1.0
 * @since <pre>Mar 19, 2020</pre>
 */
public class ExceptionTest {

	@Before
	public void before() throws Exception {
	}

	@After
	public void after() throws Exception {
	}

	/**
	 * Method: accept(T t, P1 p1, P2 p2, P3 p3)
	 */
	@Ignore
	@Test
	public void testAcceptForTP1P2P3() throws Exception {
		Object a = null;
//		try {
//			USER_NOT_FOUND.assertNotNull(a,"{} is null","a");
//		} catch (BaseException e) {
//			String trace = e.getTrace();
//      System.out.println(trace);
//		}
//		if (1==1){
//			throw new BaseException("测试{}","抛异常");
////			throw  new BaseException("aa","av");
//		}

	}


} 
